name: Publish

on:
  push:
    branches: [ main ]
    paths: [ Dockerfile ]

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: somespecialone/deta-rust-builder:latest
          # don't need the cache in such a simple case
